Added thermostat feature for heaters
zyonse/homebridge-dreo pull request #30
Opened 2023-11-30 13:59 UTC by joshuaswilcox

Add Wall heater

2023-11-30 18:55 UTC, zyonse commented
Thanks for the pull request, it looks like the changes you made to platform.ts should also fix #27

2023-11-30 18:59 UTC, joshuaswilcox commented
> Thanks for the pull request, it looks like the changes you made to platform.ts should also fix #27

Yeah I believe they should. It seems that there is just a different json shape for some of their products

2023-11-30 19:04 UTC, zyonse requested changes

2023-11-30 19:04 UTC, zyonse commented on src/platform.ts
> +          case 'fan':
Does Dreo actually use the name 'fan' for any devices in their API? Mine is named 'Tower Fan' which causes the plugin to skip over it and print 'error, unknown device type'

2023-11-30 19:47 UTC, joshuaswilcox commented on src/platform.ts
> +          case 'Air Circulator':
Oh much better!

2023-11-30 21:51 UTC, zyonse requested changes

2023-12-04 16:44 UTC, zyonse commented
Can you post a screenshot of the HomeKit heater controls on your version? Does it still show a "cool" mode?

2023-12-04 21:57 UTC, joshuaswilcox commented
> Can you post a screenshot of the HomeKit heater controls on your version? Does it still show a "cool" mode?

Yeah it still has the "cool" options, i couldnt figure out what to do about that, it seems that the only way to get the heat controls was with at "thermostat"  service but that also means it assumes it can cool.
<img width="298" alt="Screenshot 2023-12-04 at 4 51 56 PM" src="https://github.com/zyonse/homebridge-dreo/assets/512078/f1b289c0-ff69-45f0-ac71-c72749147de5">

2024-01-02 23:08 UTC, jbyerline commented
I am also interested in this feature. I have a dreo 1500w floor space heater I would like to make HomeKit compatible. I'm unsure if these changes would work for other models but if it gets merged I can try it out once I have the heater in hand.

2024-01-10 15:16 UTC, zyonse commented
Something like this might work: https://github.com/zyonse/homebridge-pentair-screenlogic/commit/a2f5f79cc79f8b321b87c5a34d0e86854df9fd5d

2024-02-04 23:52 UTC, mja00 commented
Any update on this? I've added a new heater to my Dreo account and now the plugin crashes lol

2024-05-24 07:32 UTC, zyonse commented
Closing this due to inactivity. Feel free to open a new pull request when the requested changes are implemented

2024-05-24 07:32 UTC, closed without merging